In [22]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [23]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [24]:
df.shape

(569, 33)

In [25]:
df.drop(columns=['id','Unnamed: 32'] , inplace=True)

In [26]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [27]:
x_train, x_test , y_train , y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [28]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [29]:
x_train

array([[ 0.05130462,  0.70934918,  0.19897866, ...,  0.96789937,
        -0.07456697,  1.58743027],
       [ 2.61136991,  1.78104616,  2.76438542, ...,  2.39332925,
         0.49175245,  0.18677951],
       [ 0.28069101,  0.15927462,  0.35829009, ...,  1.46409332,
        -0.0905647 , -0.10233058],
       ...,
       [ 0.10511131, -0.94324551,  0.09838252, ...,  0.68822642,
        -0.31933214, -0.40403448],
       [ 1.1217744 , -0.54728667,  1.06451602, ...,  0.59199487,
        -0.07776652, -0.10725859],
       [-0.88323248,  0.5196683 , -0.80780389, ...,  0.42509327,
         0.11740571,  0.6489176 ]], shape=(455, 30))

In [30]:
y_train

62     M
202    M
94     M
184    M
11     M
      ..
247    B
198    M
148    B
444    M
41     M
Name: diagnosis, Length: 455, dtype: object

In [31]:
label = LabelEncoder()
y_train = label.fit_transform(y_train)
y_test = label.transform(y_test)

In [32]:
y_train

array([1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1])

Numpy to PyTorch tensor

In [33]:
x_train = torch.from_numpy(x_train)
x_test = torch.from_numpy(x_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)

In [34]:
y_test

tensor([1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
        0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1])

In [35]:
x_train.shape

torch.Size([455, 30])

Defining the MODEL

In [54]:
class MySimpleNN():
    
    def __init__(self , X):
        self.weights = torch.rand(X.shape[1],1 , dtype=torch.float64 , requires_grad=True)
        self.bias = torch.zeros(1 , dtype=torch.float64 , requires_grad=True)
        
    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss(self, y_pred, y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon,1-epsilon)
        return -(y*torch.log(y_pred) + (1- y)*torch.log(1-y_pred)).mean()

In [55]:
learning_rate = 0.1
epochs = 25

Training PipeLine

In [57]:
model = MySimpleNN(x_train)
for epoch in range(epochs):
    
    #forward pass
    y_pred = model.forward(x_train)
    
    #loss calculate
    loss= model.loss(y_pred, y_train)
    
    
    #backward pass 
    loss.backward()
    #parameter update
    with torch.no_grad():
        model.weights -= learning_rate*model.weights.grad
        model.bias -= learning_rate*model.bias.grad
    
    #zero grad for next epoch not needed accumulate for grad
    model.weights.grad.zero_()
    model.weights.grad.zero_()
    
    print(loss.item())

3.3114629659270967
3.17912577108121
3.0474490101639415
2.910843116833516
2.769386426450558
2.622455283720484
2.475151834832033
2.328061785340733
2.185707400001973
2.04687438036814
1.909498447012019
1.773052322187787
1.6416030296253437
1.5168450892832759
1.4052372700461158
1.3081425442696095
1.2260217761872156
1.1581073252297471
1.1027159278714656
1.0570799068617507
1.0183529091837693
0.9869886333509903
0.9615573557402356
0.9408080606358209
0.9236318427160304

In [58]:
model.weights, model.bias

(tensor([[-0.2010],
         [-0.0220],
         [-0.1557],
         [-0.0334],
         [ 0.3243],
         [-0.3728],
         [-0.2751],
         [ 0.0501],
         [ 0.2808],
         [ 0.0942],
         [ 0.1536],
         [ 0.4176],
         [ 0.4032],
         [ 0.0856],
         [ 0.1256],
         [ 0.1852],
         [ 0.4988],
         [ 0.2204],
         [ 0.0500],
         [ 0.3180],
         [-0.0141],
         [ 0.4688],
         [ 0.0577],
         [-0.2311],
         [-0.2298],
         [ 0.4433],
         [-0.3018],
         [-0.0259],
         [-0.1287],
         [-0.3837]], dtype=torch.float64, requires_grad=True),
 tensor([-1.3873], dtype=torch.float64, requires_grad=True))

In [59]:
#model evaluation
with torch.no_grad():
    y_pred = model.forward(x_test)

In [60]:
y_pred

tensor([[0.8483],
        [0.1985],
        [0.6907],
        [0.1182],
        [0.1073],
        [0.1576],
        [0.7439],
        [0.5195],
        [0.7753],
        [0.4058],
        [0.4424],
        [0.1323],
        [0.0891],
        [0.3947],
        [0.0572],
        [0.0361],
        [0.2392],
        [0.8013],
        [0.2237],
        [0.0954],
        [0.1276],
        [0.4343],
        [0.1176],
        [0.0421],
        [0.3427],
        [0.1011],
        [0.0902],
        [0.0633],
        [0.0666],
        [0.0248],
        [0.1387],
        [0.2156],
        [0.2536],
        [0.1133],
        [0.1112],
        [0.8534],
        [0.1475],
        [0.0678],
        [0.0376],
        [0.8155],
        [0.0538],
        [0.0935],
        [0.8523],
        [0.0843],
        [0.1303],
        [0.0995],
        [0.9892],
        [0.0636],
        [0.0248],
        [0.9109],
        [0.5875],
        [0.0433],
        [0.0143],
        [0.2628],
        [0.7576],
        [0.4288],
        [0.0421],
        [0.4963],
        [0.0347],
        [0.0215],
        [0.1400],
        [0.5419],
        [0.5762],
        [0.2951],
        [0.6826],
        [0.3180],
        [0.5356],
        [0.4415],
        [0.1377],
        [0.1573],
        [0.9958],
        [0.7122],
        [0.0346],
        [0.0740],
        [0.1129],
        [0.6631],
        [0.0614],
        [0.9874],
        [0.6524],
        [0.0654],
        [0.0476],
        [0.2480],
        [0.1139],
        [0.8163],
        [0.4446],
        [0.0630],
        [0.9525],
        [0.0297],
        [0.6085],
        [0.2780],
        [0.0251],
        [0.8328],
        [0.3153],
        [0.5465],
        [0.0612],
        [0.0427],
        [0.1519],
        [0.1198],
        [0.0507],
        [0.0471],
        [0.4143],
        [0.8081],
        [0.1809],
        [0.2597],
        [0.6475],
        [0.1355],
        [0.4679],
        [0.8332],
        [0.2538],
        [0.1737],
        [0.0587],
        [0.4001],
        [0.1222],
        [0.3559]], dtype=torch.float64)

In [61]:
y_pred = (y_pred > 0.5 ).float()
y_pred

tensor([[1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [62]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)

0.5263157894736842