In [225]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [226]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [227]:
df.shape

(569, 33)

In [228]:
df.drop(columns=['id','Unnamed: 32'] , inplace=True)

In [229]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [230]:
x_train, x_test , y_train , y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [231]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [232]:
x_train

array([[ 1.28489073, -0.19226612,  1.25550868, ...,  0.82696846,
         1.365312  ,  0.12952134],
       [ 0.38232962, -1.17965295,  0.47500108, ...,  2.01164901,
         2.99878001,  0.90276439],
       [ 0.15090369,  1.89839802,  0.23287587, ...,  0.93739141,
         2.24422534,  2.86217473],
       ...,
       [ 0.91750207,  0.63055625,  0.85686233, ...,  1.36646347,
         0.56034165, -0.44121915],
       [-0.10366483, -0.05087974, -0.07219349, ...,  0.45626283,
        -0.23286504,  0.27659024],
       [-0.50576737,  2.46162573, -0.5774253 , ..., -1.76323855,
        -0.79584012, -0.9090114 ]], shape=(455, 30))

In [233]:
y_train

85     M
22     M
15     M
334    B
333    B
      ..
496    B
154    B
264    M
423    B
473    B
Name: diagnosis, Length: 455, dtype: object

In [234]:
label = LabelEncoder()
y_train = label.fit_transform(y_train)
y_test = label.transform(y_test)

In [235]:
y_train

array([1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0])

Numpy to PyTorch tensor

In [236]:
x_train = torch.from_numpy(x_train)
x_test = torch.from_numpy(x_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)

In [237]:
y_test

tensor([1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1])

In [238]:
x_train.shape

torch.Size([455, 30])

Defining the MODEL

In [239]:
import torch
import torch.nn as nn

In [240]:
class MySimpleNN(nn.Module):
    
    def __init__(self , num_features):
        
        super().__init__()
        
        self.linear = nn.Linear(num_features , 1)
        self.sigmoid = nn.Sigmoid()
        
        
    def forward(self, features):
        
        out = self.linear(features)
        out = self.sigmoid(out)
        
        return out

In [241]:
learning_rate = 0.1
epochs = 25

In [242]:
loss_function= nn.BCELoss()

Training PipeLine

In [243]:
model = MySimpleNN(x_train.shape[1])
optimizer = torch.optim.SGD(model.parameters() ,lr= learning_rate)
for epoch in range(epochs):
    
    #forward pass
    y_pred = model(x_train.float())
    
    #loss calculate
    loss = loss_function(y_pred, y_train.float().view(-1,1))
    
    #zero grad for next epoch not needed accumulate for grad
    # It is better to make it zero before calculation than after 
    optimizer.zero_grad()
    #backward pass 
    loss.backward()
    #parameter update
    optimizer.step()
    
    print(loss.item())

0.8560923933982849
0.636918842792511
0.5188500285148621
0.4489355981349945
0.401876300573349
0.36746591329574585
0.3409053683280945
0.3196088373661041
0.3020452558994293
0.2872428894042969
0.2745514512062073
0.2635171115398407
0.2538122534751892
0.24519357085227966
0.23747612535953522
0.23051650822162628
0.22420156002044678
0.2184404581785202
0.21315951645374298
0.20829808712005615
0.20380567014217377
0.19963997602462769
0.19576504826545715
0.19215022027492523
0.18876902759075165

In [244]:
model.linear.weight, model.linear.bias

(Parameter containing:
 tensor([[ 0.2597,  0.1512,  0.4050,  0.3086,  0.0810,  0.2242,  0.1878,  0.1210,
           0.0662,  0.0103,  0.0854,  0.0103,  0.3270,  0.0350,  0.0427,  0.0112,
           0.0137,  0.0996, -0.1368, -0.0055,  0.2402,  0.2628,  0.2285,  0.1329,
           0.1468,  0.2038,  0.0380,  0.2671,  0.2847, -0.0723]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.1972], requires_grad=True))

In [245]:
#model evaluation
with torch.no_grad():
    y_pred = model.forward(x_test.float())

In [246]:
y_pred

tensor([[0.9991],
        [0.9503],
        [0.0066],
        [0.3018],
        [0.0237],
        [0.9887],
        [0.9989],
        [1.0000],
        [0.9828],
        [0.1419],
        [0.9179],
        [0.9574],
        [0.0507],
        [0.3492],
        [0.0607],
        [0.5619],
        [0.9946],
        [0.8173],
        [0.9969],
        [0.2027],
        [0.0472],
        [0.0449],
        [0.6806],
        [0.9925],
        [0.9921],
        [0.0896],
        [0.1102],
        [0.2327],
        [0.5088],
        [0.0252],
        [0.9989],
        [0.9394],
        [0.9996],
        [0.6062],
        [0.2948],
        [0.0290],
        [0.9961],
        [0.4039],
        [0.0866],
        [0.0579],
        [0.0854],
        [0.2166],
        [0.1131],
        [0.9274],
        [0.9436],
        [0.2528],
        [0.1873],
        [0.2283],
        [0.9787],
        [0.9934],
        [0.2008],
        [0.8733],
        [0.4297],
        [0.9891],
        [0.0393],
        [0.6322],
        [0.2407],
        [0.8665],
        [0.0589],
        [0.8457],
        [0.0351],
        [0.4415],
        [0.0316],
        [0.1809],
        [0.8081],
        [0.9253],
        [0.0129],
        [0.0336],
        [0.2530],
        [0.0791],
        [0.3036],
        [0.0777],
        [0.0719],
        [0.5867],
        [0.0338],
        [0.0665],
        [0.4377],
        [0.0830],
        [0.2045],
        [0.0198],
        [0.0574],
        [0.1141],
        [0.9654],
        [0.9316],
        [0.0841],
        [0.0387],
        [0.9817],
        [0.8177],
        [0.9878],
        [0.9969],
        [0.2827],
        [0.0535],
        [0.9883],
        [0.0325],
        [0.9543],
        [0.1164],
        [0.1606],
        [0.8854],
        [0.1543],
        [0.9904],
        [0.8514],
        [0.9392],
        [0.0286],
        [0.9411],
        [0.0318],
        [0.9803],
        [0.9930],
        [0.9955],
        [0.0169],
        [0.0082],
        [0.0868],
        [0.9882],
        [0.0041],
        [0.5149]])

In [247]:
y_pred = (y_pred > 0.5 ).float()
y_pred

tensor([[1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.]])

In [248]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)

0.9912280701754386