In [77]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [78]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [79]:
df.shape

(569, 33)

In [80]:
df.drop(columns=['id','Unnamed: 32'] , inplace=True)

In [81]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [82]:
x_train, x_test , y_train , y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [83]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [84]:
x_train

array([[-0.48413657, -0.39010711, -0.42522326, ..., -0.63414043,
        -0.58220576,  0.53114515],
       [-0.32647871, -0.7718446 , -0.35564835, ..., -0.14241678,
         0.76692914,  0.65786705],
       [-1.23315472,  0.12960779, -1.2317923 , ..., -1.40317155,
        -1.60060613,  0.32219483],
       ...,
       [ 1.10104153,  1.17363683,  0.98002333, ..., -0.01910051,
        -0.66734534, -0.26354193],
       [-0.34941076, -0.72815176, -0.38731118, ..., -0.87923153,
         1.13368426, -0.7625446 ],
       [ 1.84060021,  1.93941144,  1.77992651, ...,  0.63910011,
        -0.77704442, -0.04952273]], shape=(455, 30))

In [85]:
y_train

431    B
292    B
97     B
178    B
204    B
      ..
150    B
201    M
274    M
268    B
233    M
Name: diagnosis, Length: 455, dtype: object

In [86]:
label = LabelEncoder()
y_train = label.fit_transform(y_train)
y_test = label.transform(y_test)

In [87]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1])

Numpy to PyTorch tensor

In [88]:
x_train = torch.from_numpy(x_train)
x_test = torch.from_numpy(x_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)

In [89]:
y_test

tensor([0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
        1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1])

In [90]:
x_train.shape

torch.Size([455, 30])

Defining the MODEL

In [91]:
from torch.utils.data import Dataset, DataLoader

In [92]:
class CustomDataset(Dataset):
    
    def __init__(self, features , labels):
        
        self.features = features
        self.labels = labels
        
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index] , self.labels[index]

In [93]:
train_dataset = CustomDataset(x_train, y_train)
test_dataset = CustomDataset(x_test , y_test)

In [94]:
train_dataset[10]

(tensor([-0.3551,  0.4585, -0.3769, -0.3956, -1.4801, -0.4001, -0.3500, -0.7903,
         -0.8726, -0.2422,  0.3803,  0.9835, -0.1507,  0.0393, -0.3344,  1.0600,
          0.6148,  0.2523,  0.6924,  1.4745, -0.3831,  0.1845, -0.4617, -0.4095,
         -1.7019, -0.3953, -0.4366, -0.9068, -0.6935, -0.1492],
        dtype=torch.float64),
 tensor(0))

In [95]:
train_loader = DataLoader(train_dataset , batch_size=32 , shuffle=True)
test_loader = DataLoader(test_dataset , batch_size=32 , shuffle=True)

In [96]:
import torch
import torch.nn as nn

In [97]:
class MySimpleNN(nn.Module):
    
    def __init__(self , num_features):
        
        super().__init__()
        
        self.linear = nn.Linear(num_features , 1)
        self.sigmoid = nn.Sigmoid()
        
        
    def forward(self, features):
        
        out = self.linear(features)
        out = self.sigmoid(out)
        
        return out

In [98]:
learning_rate = 0.1
epochs = 25

In [99]:
model = MySimpleNN(x_train.shape[1])
optimizer = torch.optim.SGD(model.parameters() ,lr= learning_rate)
loss_function= nn.BCELoss()

Training PipeLine

In [100]:

for epoch in range(epochs):
    
    for batch_features , batch_labels in train_loader:
        # Convert to float32 for compatibility with model
        batch_features = batch_features.float()
        batch_labels = batch_labels.float()
        
        #forward pass
        y_pred = model(batch_features)
        
        #loss calculate
        loss = loss_function(y_pred, batch_labels.view(-1,1))
        
        #zero grad for next epoch not needed accumulate for grad
        # It is better to make it zero before calculation than after 
        optimizer.zero_grad()
        #backward pass 
        loss.backward()
        #parameter update
        optimizer.step()
        
        print(loss.item())

0.5917378664016724
0.5023120641708374
0.3807840943336487
0.3998999297618866
0.41964149475097656
0.36639702320098877
0.3756979703903198
0.2889895439147949
0.319125235080719
0.23466867208480835
0.17239990830421448
0.280934602022171
0.20080295205116272
0.17076347768306732
0.18621240556240082
0.24036629498004913
0.19003361463546753
0.20351293683052063
0.08528584241867065
0.17722156643867493
0.33800122141838074
0.10814216732978821
0.2001778781414032
0.1764877885580063
0.20727556943893433
0.11291255056858063
0.15349003672599792
0.15960699319839478
0.1598135530948639
0.18364670872688293
0.10579673200845718
0.19495370984077454
0.16320398449897766
0.1334691196680069
0.16872866451740265
0.09232033789157867
0.13741958141326904
0.1622103452682495
0.07966747879981995
0.11976273357868195
0.161888986825943
0.12060415744781494
0.11995897442102432
0.20332710444927216
0.14600543677806854
0.08077554404735565
0.11157085746526718
0.1259976625442505
0.09957569092512131
0.12218571454286575
0.1996595859527588
0.16911733150482178
0.08463510870933533
0.12704984843730927
0.1798190474510193
0.08373089134693146
0.12021312117576599
0.04891281574964523
0.10020478069782257
0.28396156430244446
0.06813841313123703
0.1015271469950676
0.053407248109579086
0.1597905308008194
0.184197336435318
0.13316825032234192
0.11238361895084381
0.08460405468940735
0.10399657487869263
0.15751361846923828
0.07791651040315628
0.11797163635492325
0.09157578647136688
0.08559364080429077
0.11680280417203903
0.0687299519777298
0.09314125031232834
0.116050586104393
0.1021588146686554
0.082317054271698
0.11648212373256683
0.05054964870214462
0.09341052174568176
0.11607888340950012
0.0787167027592659
0.05136296898126602
0.23861941695213318
0.12178623676300049
0.10086481273174286
0.04601438716053963
0.12648597359657288
0.04757547006011009
0.06250618398189545
0.13855576515197754
0.05943334102630615
0.061104074120521545
0.09447234123945236
0.11595860123634338
0.16947758197784424
0.04493822157382965
0.1178431361913681
0.06440791487693787
0.14738118648529053
0.07031750679016113
0.12335716187953949
0.08478420972824097
0.04869954288005829
0.07609911262989044
0.08283047378063202
0.10493198782205582
0.1410965770483017
0.1284123659133911
0.06181766465306282
0.05310111492872238
0.05483907461166382
0.15087461471557617
0.04747231304645538
0.09797818213701248
0.12673529982566833
0.061446044594049454
0.05619509145617485
0.07371033728122711
0.05692461133003235
0.08229141682386398
0.18862545490264893
0.07588326930999756
0.0993095189332962
0.03774744272232056
0.09457610547542572
0.10594165325164795
0.08236704766750336
0.06953495740890503
0.11567757278680801
0.05976877361536026
0.07095713913440704
0.11193472146987915
0.04453444108366966
0.1281069666147232
0.07769683748483658
0.0526922233402729
0.0377618670463562
0.17923438549041748
0.07147834450006485
0.078018419444561
0.03724049776792526
0.06269645690917969
0.15519565343856812
0.03326001390814781
0.09519435465335846
0.01026986725628376
0.09314113855361938
0.07821644842624664
0.11565127223730087
0.05851219967007637
0.16767869889736176
0.034873902797698975
0.09672210365533829
0.10317446291446686
0.034786924719810486
0.04260428249835968
0.09633858501911163
0.05461953207850456
0.07975560426712036
0.06209390610456467
0.049864787608385086
0.047822415828704834
0.05007743090391159
0.0876467302441597
0.06236674636602402
0.09852834045886993
0.0680614784359932
0.06987611204385757
0.02021075040102005
0.18523193895816803
0.04574168473482132
0.03441757708787918
0.14347270131111145
0.0813756138086319
0.08815275132656097
0.04233180731534958
0.0236224215477705
0.10607782006263733
0.03812117129564285
0.055069949477910995
0.128571018576622
0.1193222776055336
0.08468183875083923
0.06573977321386337
0.08218500018119812
0.11977788805961609
0.06294064223766327
0.07330954819917679
0.049488089978694916
0.05007307231426239
0.019729452207684517
0.04621490091085434
0.11283242702484131
0.04129651188850403
0.11563162505626678
0.03737853094935417
0.059610314667224884
0.08487959206104279
0.16915740072727203
0.06467276066541672
0.03492189571261406
0.06607728451490402
0.04105190187692642
0.05338027700781822
0.09645810723304749
0.06187060475349426
0.13385018706321716
0.11574821919202805
0.07452799379825592
0.04651736840605736
0.044048432260751724
0.05580320954322815
0.05674862116575241
0.08148471266031265
0.020117267966270447
0.039802923798561096
0.1359456479549408
0.04577582702040672
0.06461362540721893
0.07259257882833481
0.11578836292028427
0.09595077484846115
0.03520942106842995
0.039034079760313034
0.042182210832834244
0.10991641879081726
0.06118714436888695
0.04655449464917183
0.06788181513547897
0.11298772692680359
0.0494537390768528
0.09160509705543518
0.08322151005268097
0.06642709672451019
0.05919288098812103
0.13818134367465973
0.038767870515584946
0.04177474230527878
0.02341519668698311
0.14287981390953064
0.045430928468704224
0.0444178581237793
0.0989135354757309
0.08343039453029633
0.014318985864520073
0.104911670088768
0.06285429000854492
0.037344951182603836
0.07629434764385223
0.1463572382926941
0.04420848563313484
0.05041196197271347
0.11831209063529968
0.07829944789409637
0.051547154784202576
0.05124972015619278
0.1143941655755043
0.10619287192821503
0.023199917748570442
0.07046356052160263
0.047590866684913635
0.0520387664437294
0.0411619171500206
0.06900455057621002
0.06473325937986374
0.07429307699203491
0.03174703195691109
0.02740180492401123
0.021112076938152313
0.13221992552280426
0.01772608980536461
0.06252627074718475
0.07553023844957352
0.13431885838508606
0.06730009615421295
0.050409261137247086
0.04149771109223366
0.07292750477790833
0.06631159782409668
0.13519015908241272
0.0012277427595108747
0.05646621808409691
0.030203741043806076
0.14302808046340942
0.02116112969815731
0.07918098568916321
0.02373562939465046
0.11736015230417252
0.0691690444946289
0.051732636988162994
0.11443395167589188
0.05185477435588837
0.07443095743656158
0.04334096610546112
0.045111943036317825
0.006900664884597063
0.053324759006500244
0.06272424757480621
0.04517405107617378
0.05935519188642502
0.06483282148838043
0.020313896238803864
0.06981438398361206
0.11308276653289795
0.1296907663345337
0.11825837939977646
0.028282880783081055
0.05602817237377167
0.04098968207836151
0.047101940959692
0.006025595124810934
0.06550407409667969
0.021962272003293037
0.0367891900241375
0.03031841665506363
0.053968463093042374
0.17584645748138428
0.04539412632584572
0.13795335590839386
0.039317984133958817
0.049853142350912094
0.03582172095775604
0.144159734249115
0.021065132692456245
0.03678768500685692
0.012708500027656555
0.052312977612018585
0.04883216693997383
0.13074272871017456
0.04774629697203636
0.10018456727266312
0.06656662374734879
0.07632706314325333
0.060581106692552567
0.0884903073310852
0.06272892653942108
0.014294935390353203
0.025394778698682785
0.04556666314601898
0.03843159228563309
0.12662656605243683
0.0650084912776947
0.048939041793346405
0.022630194202065468
0.11150059103965759
0.11056536436080933
0.15427306294441223
0.06291376054286957
0.05010560154914856
0.049436137080192566
0.0824740082025528
0.04200189933180809
0.019754892215132713
0.028772778809070587
0.025328876450657845
0.005080182105302811
0.13780055940151215
0.022335536777973175
0.032119251787662506
0.0402270145714283
0.030857782810926437
0.03074648417532444
0.03873355686664581
0.0802510529756546
0.07433199882507324
0.03843246400356293
0.10829393565654755
0.0649966225028038
0.12357533723115921
0.03104848973453045
0.045104797929525375

In [101]:
model.linear.weight, model.linear.bias

(Parameter containing:
 tensor([[ 0.3674,  0.5765,  0.5776,  0.4860,  0.2698,  0.1735,  0.3400,  0.5435,
           0.2439, -0.2582,  0.6023, -0.1127,  0.3328,  0.4489,  0.1378, -0.2394,
          -0.1076,  0.1039, -0.1027, -0.3633,  0.6613,  0.9023,  0.7750,  0.6085,
           0.4930,  0.2336,  0.4328,  0.6752,  0.2784,  0.0622]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.6048], requires_grad=True))

In [102]:
#model evaluation
model.eval()
accuracy_list= []

with torch.no_grad():
    for batch_features , batch_labels in test_loader:
        # Convert batch_features to float32 for compatibility
        batch_features = batch_features.float()
        
        y_pred = model(batch_features)
        y_pred = (y_pred>0.8).float()
        
        batch_accuracy = (y_pred.view(-1)== batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)
    
overall_accuracy = sum(accuracy_list)/ len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9453